### ISSUE TITLE
Impossible de télécharger les news

### ISSUE THREAD

**Issue by N0ciple** [sylvaindurand/calibre#1]
Bonjour, 

il m'est impossible de télécharger les dernières news via votre recette. Voici un extrait du message d'erreur :

>  InputFormatPlugin: Recipe Input running
> Using custom recipe
> Vos identifiants sont incorrects, ou votre abonnement LeMonde.fr ne vous permet pas de télécharger le journal.
> Python function terminated unexpectedly
>   No articles found, aborting (Error Code: 1)
> Traceback (most recent call last):
>   File "site.py", line 132, in main
>   File "site.py", line 109, in run_entry_point
>   File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
>   File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
>   File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
>   File "site-packages\calibre\customize\conversion.py", line 245, in __call__
>   File "site-packages\calibre\ebooks\conversion\plugins\recipe_input.py", line 119, in convert
>   File "site-packages\calibre\web\feeds\news.py", line 1001, in download
>   File "site-packages\calibre\web\feeds\news.py", line 1176, in build_index
> ValueError: No articles found, aborting

Je suis absolument sûr d'avoir entré correctement mes identifiants et je dispose d'un abonnement. 
J'ai essayé sous un ordinateur sous windows et sous mac. 

Sous windows avec la commande ebook-convert, j'obtient ceci :
 

> 
> 1% Conversion de l’entrée en HTML…
> InputFormatPlugin: Recipe Input running
> Qt: Untested Windows version 10.0 detected!
> Python function terminated unexpectedly
>   'utf8' codec can't decode byte 0xe0 in position 502: invalid continuation byte (Error Code: 1)
> Traceback (most recent call last):
>   File "site.py", line 132, in main
>   File "site.py", line 109, in run_entry_point
>   File "site-packages\calibre\ebooks\conversion\cli.py", line 393, in main
>   File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
>   File "site-packages\calibre\customize\conversion.py", line 245, in __call__
>   File "site-packages\calibre\ebooks\conversion\plugins\recipe_input.py", line 73, in convert
>   File "site-packages\calibre\web\feeds\recipes\__init__.py", line 36, in compile_recipe
>   File "encodings\utf_8.py", line 16, in decode
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 502: invalid continuation byte

Savez vous si LeMonde a modifié le format de son contenu ce qui rend la recette non opérationnelle ou bien le problème vient de mon côté ? 

Merci d'avance !

**Comment by sylvaindurand** [comment]
Hélas, je ne suis moi-même plus abonné, donc en l'absence d'identifiants, je ne peux pas le savoir ni, le cas échéant, le corriger :/
